language: ruby
rvm:
  - 2.2.3
before_install: npm install -g grunt-cli
install: npm install
#before_script: grunt pre-build
script:
	- grunt pre-build
  - bundle exec jekyll build
  - grunt min
#  - bundle exec htmlproofer ./_site --only-4xx --check-html
branches:
  only:
  - master
#  - gh-pages
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
# deploy to netlify
after_success:
  - chmod +x ./scripts/deploy.sh
  - ./scripts/deploy.sh
